### ISSUE TITLE
404 on register and login

### ISSUE THREAD

**Issue by Rusty666** [irabbi360/laravel-vue3-spa-starter#6]
Register and login buttons give me a 404

Failed to load resource: the server responded with a status of 404 (Not Found) register:1 
        
POST http://localhost/login 404 (Not Found)

![image](https://user-images.githubusercontent.com/72977113/227736006-26429a76-7821-463d-99ab-a9e771527ef6.png)

Running on Windows IIS. The home page and blog page come up fine.

**Comment by irabbi360** [comment]
please set app url on .env I hope it'll be fixed.

**Comment by Rusty666** [comment]
APP_URL=http://localhost

 The home page and blog page come up fine, any of the authentication pages do not
