### ISSUE TITLE
missing features forgot password, reset password, user management.

### ISSUE THREAD

**Issue by delebash** [irabbi360/laravel-vue3-spa-starter#9]
Thank you very much for this.  A couple of routes that seem to be missing are the ones listed above. 

Like in the default breeze example in the routes auth.php it has 

```
Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])
                ->middleware('guest')
                ->name('password.email');

Route::post('/reset-password', [NewPasswordController::class, 'store'])
                ->middleware('guest')
                ->name('password.store');

Route::get('/verify-email/{id}/{hash}', VerifyEmailController::class)
                ->middleware(['auth', 'signed', 'throttle:6,1'])
                ->name('verification.verify');

Route::post('/email/verification-notification', [EmailVerificationNotificationController::class, 'store'])
                ->middleware(['auth', 'throttle:6,1'])
                ->name('verification.send');
```

I am guessing I could just add these to the web.php but since you had this listed as a feature and user management, I wanted to make sure I was not missing something.  Cheers!

**Comment by irabbi360** [comment]
You're welcome! I'm grateful for your input. Indeed, those routes are absent. If you're interested, you're welcome to contribute to their addition. Alternatively, I can take care of adding them, but there might be times when I'll need your assistance with them.

**Comment by delebash** [comment]
Thanks. I would be happy to contribute but right now I am very new to Laravel and am using this as a learning project.

**Comment by irabbi360** [comment]
forgot password, password reset add on API & Frontend. Verification will be added soon.

**Comment by delebash** [comment]
awesome!

**Comment by irabbi360** [comment]
user management add done. pull the latest code. User Verification will be added soon.

**Comment by delebash** [comment]
Thank you very much for this project.  Cheers!
